#include "command.h"

using namespace mmkv::protocol;

std::string mmkv::protocol::detail::command_strings[] = {
  "stradd",
  "strdel",
  "strget",
  "strset",
  "strlen",
  "strappend",
  "strpopback",
  "ladd",
  "lappend",
  "lprepend",
  "lgetsize",
  "lgetall",
  "lgetrange",
  "lpopfront",
  "lpopback",
  "ldel",
  "vadd",
  "vdelm",
  "vdelmrange",
  "vdelmrangebyweight",
  "vsize",
  "vsizebyweight",
  "vweight",
  "vorder",
  "vrorder",
  "vrange",
  "vall",
  "vrangebyweight",
  "vrrange",
  "vrrangebyweight",
  "madd",
  "mset",
  "mget",
  "mgets",
  "mdel",
  "mall",
  "mfields",
  "mvalues",
  "msize",
  "mexists",
  "sadd",
  "sdelm",
  "ssize",
  "sall",
  "sexists",
  "sand",
  "sandto",
  "ssub",
  "ssubto",
  "sor",
  "sorto",
  "sandsize",
  "ssubsize",
  "sorsize",
  "memorystat",
  "expireat",
  "expireafter",
  "del",
  "rename",
  "type",
  "keyall"
};

static_assert(sizeof(mmkv::protocol::detail::command_strings) / sizeof(std::string) == COMMAND_NUM, "The size of command_strings must be equal to the number of the commands");
